---
apiVersion: skyline.local/v1 # Ne jamais modifier ici
kind: CTFChallenge # Ne jamais modifier ici
metadata:
  name: gate-bypass-enzo
  namespace: ctfd # Ne jamais modifier ici
spec:
  name: "Gate Bypass"
  description: |
    Le nouveau système de sécurité de SKL Corp utilise une porte d'accès protégée par un login/mot de passe. Cependant, un employé mécontent a laissé entendre que la base de données était mal configurée... Parviendras-tu à contourner l'authentification pour récupérer le flag caché dans le panneau d'administration ?
  category: "Web"
  points: 100
  type: "standard"
  state: "visible"
  instance: True
  connection_info: "Lancer votre instance sur http://deployer.ctfd.tail575cd.ts.net"
  max_attempts: 0
  image: "nginx:latest"
  port: 80
  creator: "Enzo"
