apiVersion: skyline.local/v1
kind: CTFChallenge
metadata:
    name: cellule-4755
    namespace: ctfd
spec:
    name: Cellule 4755
    description: Brute forcez le SSH et exploitez le binaire SUID.
    category: System
    points: 100
    image: ghcr.io/sp00kyskelet0n/skylinectf-challenges/cellule-4755:latest
    port: 22
    flag: ENC[AES256_GCM,data:d93wh2QryyO3dXTyEDtsbGFVxC+bIUEc8w==,iv:5dsMt9+0IDGRwqBG3tAGr2QvvO2FA6Fm80RUzkfJ8hk=,tag:CQRJg2iSvveOIQHDHZKQxA==,type:str]
sops:
    lastmodified: "2026-02-05T10:43:33Z"
    mac: ENC[AES256_GCM,data:JP2JZBJp0c6eT0/05kXr+fiRf/rox7Jg189G4XoZyxa4UcBMWt1JWEMDbB87DJjUf1doNE1R7vs3BT4WMBhYLAAhokNMhJeW4n4dYqUnsDuClsfq+ZsctiFrpDg2fFCFIudnZW3Df4EsLPtYJp5rt0R4D0QtrKdA7/NSCDil/iQ=,iv:+EiEqfa8ROKCaUH1bGTI2Rf4DsuYgqJsRpy3x7MXGBw=,tag:aatzOhknUStq1exlmExLkA==,type:str]
    pgp:
        - created_at: "2026-02-05T10:43:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9ybr2vGOZs6AQ//b+JgLBaf2v39tBdwNO+N6xzIGUBed8TP5l/PWXvay2rD
            Aa2BH1cVTrgfuNeGAwqaDbah9LeAVOJKK9cJnVl1YkLakiYaR9wcUE9n78ajt7zi
            Km7u0/9q7Lc06YAH3dL9X8PvoYuPpcE1HZixljNc1HkIQif8p0GJ5L6YgWdFKHCF
            IDTOnuvdqQvllhC1Bi6r0PO0y0/VVXt3hiBuOzV3fW2xGP2X0hVY0EzEHZCxt+C3
            d4Zn3iVIA0PMO9wIzgMBeqzZabe9/x6P7jtOa1m/ZBf+lrneskiQ8ZR2y27wETUy
            r6RkCDMq75dXF2OerkCkY8CELnelO+mlTqT2OhvDW7e1Oz7XL8UQCiKs6AbkZ4o1
            7c1+cf3vUMh2k9/2CtefehaFj7Z7BFKnaO0TPwZPRhy4WCjpXxfOVitMF8hNc/2p
            0tQABvM8GWnv1BxC18/CjjrISX1ytePdgUg+8UUo4CDv8s40A+KmzK6iMs9rCqPE
            cIjfhV1e0Yd1NIwdIhREJe8+nueIagsEkasDRUDf2sRjQZmJt1oJLR+0IjBhczpp
            +diq4LcUEm1JidO2ijVVMq7XSSDsqYj+LHIN3S7rKPX7HwSdtYjwFy1sU6Szycox
            o87I6Bs6iW040GJGI2GuYfQbH9Vub7teEAEa9vDg2SOCcs1AdbMkSyGAFovoRpjU
            aAEJAhCQzZIESIP8wJTD1cQDXcsDxavgf/kPyVISoWZHQe2QebAxUgbyB24oua/I
            2yWtajbJwlTO+v30V7ivLzfkrEmNAdbHeWDpIR+JjRU9HfijPTXejilKZE1BCzCP
            puEcXmdfkBaz
            =MMno
            -----END PGP MESSAGE-----
          fp: 96F466C4EF5AE501FC0C31649FBB4E548493AC41
    encrypted_regex: ^(data|stringData|flag|password|secret)$
    version: 3.11.0
