apiVersion: skyline.local/v1
kind: CTFChallenge
metadata:
  name: cell-block
  namespace: ctfd
spec:
  name: Ce(-l)l Block
  description: |
    Vous êtes enfermé dans un environnement restreint (rbash).
    Votre objectif est de vous évader de cette prison (jail escape) pour lire le flag.
    Identifiants SSH fournis au lancement de l'instance.
  category: System
  points: 100
  instance: true
  image: ghcr.io/sp00kyskelet0n/skylinectf-challenges/ce-l-l-block:latest
  port: 22
  flag: ENC[AES256_GCM,data:+3O+O8R1NZaLEYIytq2ELPR3,iv:Jl6vdUfX0RtjnAD0AyR/dMul83OJMmomMlxlVx6IVCg=,tag:JQ0CTHt9AGQUAi1ce/3kuA==,type:str]
sops:
  lastmodified: "2026-02-06T11:15:28Z"
  mac: ENC[AES256_GCM,data:2mQhM2+4lbP/q/d8WiHUo/hEOBh0hhQDUwZBKkbxdXArKlCZRnBvFveKqOXyoBj8vs0+CD8uDIbW9sdJQlLceEUKv+P3qGZ+AwEm2JuO3o+J91lgEKG114CX9gi2njyypvTmacXi9DzGBBzrjfAnX7YqxtcOVpMbMtpQqoK9uw=,iv:yg8BWZ7s5uyLP7xJqGMS+vQoosFr3vO/vCSx5mLZKfM=,tag:q4m7nb/IKcamnVAyBl98qA==,type:str]
  pgp:
    - created_at: "2026-02-06T08:58:07Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA4Wg+3KzyZPEAQ//dg+tQdIf7b71ZBUKNe6vptaTACs6z76N72WXKTIMe4v8
        JYxHmzmQr6XL/TSPcueTPymLkitAUjTUZrItIvp3Aq+x33zBRL5Sl+OWvPwMNXne
        DZs4JOUW7p2O9b3ddUmJR66SKduHE28zMVjLbBQotdmJuR93MVgas8JbgQgpX+lA
        5+DsM7KD4PpJAFPQ3HfvM9J8X50WNq7vRZukwYwD5cEHuGjAxWWKRxqmMTpQikCA
        cxe/gk7UKuDOj0jprWjKb4u5Dz6EvenN2ZS2IdxU8idhIK5F/e0TXNTb8Ua0HSND
        3Dap7RK2lsAoUyKVIdhCV6RCZWol/E4/pOGD9H4dycMON9+se1Hq0Jvi8iTnr8Oz
        YaQZCnQF2m8bocd1fBpufjtjqojeKODApXsAG2onQgZ/kFYznUCQR9ZyGh6Y7hVZ
        sUZsew472OjdstI6PFfl/13n2MSTAE3dYFPiAIvGoqFFq7CTZTgMuoHPYX8IJuBV
        SpJxWBhhZtM1432xI7X0+MsK/fRpV67zvXARJWweRgnlJhH/BHrAAwf0YiTmipMJ
        y64H9SgrzXaGoFQ2rE6heLk7jxrEUuCSU11gVLW8pVFwI/q7IvoOwoZhPzzq+VFr
        19J0+vhVAzTBU2QEFYk6UmSveWIEZtVS838646oasvw+qECr9grD0O6EClAqHD3U
        aAEJAhDb8YFgWb4XQtux4kw+kEqN4zm5/Tv+QxrmGeCiC8f9RG/ud2nVQYlAbCgE
        N5WHnlvW3mnqLyHS+5ZSoTybmw87ql2kSgZPJKQTnjalxlB3lotRp+WBko+HYMOT
        bNADNSgQ2JIm
        =a74G
        -----END PGP MESSAGE-----
      fp: 2F678007F08254265530095FB5B68F8BCE0CB069
  encrypted_regex: ^(data|stringData|flag|password|secret)$
  version: 3.11.0
